

####### DATA CONFIG
dataset_path: ../Datasets/Flavia/dataset.csv
image_path: ../Datasets/Flavia/Leaves
checkpoint_path: checkpoints/
logdir: logs
prediction_logdir: predictions

###### TRAINING CONFIG
restore_from_checkpoint: False
Train: True
Test: False

epochs: 150
early_stopping_patience: 4
batch_size: 64
kld_weight: 0.00025
lr: 1e-4
####### MODEL CONFIG

hidden_dims: [32, 64, 128, 256, 512]
kernel_sizes: [12, 9, 7, 3, 3]
strides: [2, 2, 2, 2, 2]

input_size: 256
input_channels: 3
latent_space_size: 16
